server:
  port: 12443
  tomcat:
    max-threads: 800
    accept-count: 30000
    min-spare-threads: 20
    max-connections: 30000
  ssl:
    key-store-type: JKS
    key-store: tomcat.key
    key-store-password: dataseek2019
http:
  port: 12006
xe:
  driver: com.mysql.jdbc.Driver
  jdbc_url: jdbc:mysql://xe-light-db1.chlw7qiuht3u.ap-southeast-2.rds.amazonaws.com:13306/xero?useUnicode=true&characterEncoding=utf8&useSSL=false
  db_username: dataseek
  db_password: Njit2018!!!!!!
  initialSize: 5
  maxActive: 10
  maxIdle: 5
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  interTrigger: false
spring:
    datasource:
        username: dataseek
        password: Njit2018!!!!!!
        jdbc-url: jdbc:mysql:// xe-light-db1.chlw7qiuht3u.ap-southeast-2.rds.amazonaws.com:13306/xero?useUnicode=true&characterEncoding=utf8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
    profiles:
        active: dev

