server:
  port: 12443
  tomcat:
    max-threads: 800
    accept-count: 30000
    min-spare-threads: 20
    max-connections: 30000
  ssl:
    key-store-type: JKS
    key-store: tomcat.key
    key-store-password: dataseek2019
http:
  port: 12006
xe:
  driver: com.mysql.jdbc.Driver
  jdbc_url: jdbc:mysql://47.101.53.114:3606/xero?useUnicode=true&characterEncoding=utf8&useSSL=false
  db_username: root
  db_password: DataSeek@2019
  initialSize: 20
  maxActive: 30
  maxIdle: 10
  minIdle: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
  interTrigger: false
spring:
    datasource:
        username: root
        password: DataSeek@2019
        jdbc-url: jdbc:mysql://47.101.53.114:3606/xero?useUnicode=true&characterEncoding=utf8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
    profiles:
        active: dev

